version: '3.9'

services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

  node:
    image: node:current
    build:
      context: .
      target: node
    ports:
      - 127.0.0.1:8000:8555

  reverse-proxy:
    image: node-reverse-proxy:current
    build:
      context: .
      target: reverse-proxy
